import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const Barlow = Barlow_Condensed({
  subsets: ["latin"],
  weight: '400',
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${Barlow.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  );
}
